New-Item -ItemType Directory -Path .github\workflows -Force | Out-Null
@'
name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: master  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get
      - run: flutter build web --release --base-href "/"

      # SPA: tránh 404 khi F5 ở route con
      - run: cp build/web/index.html build/web/404.html

      # tránh Jekyll can thiệp file bắt đầu bằng "_"
      - run: touch build/web/.nojekyll

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
'@ | Set-Content .github/workflows/deploy.yml
